### PR TITLE
Update AppInsights Core to 3.0.9

### PR DESCRIPTION
**Pull request by Karlie-777**

### CODE REVIEW

**Review by MSNev — CHANGES_REQUESTED** [review]
We don't need to update this version as this was unaffected by the memory issue

**Comment by MSNev** [comment]
It's only v4.1.0 and 4.0.3 that we need to update.

**Comment by Karlie-777** [comment]
no need to update this version

**Comment by MSNev** [comment]
But I see we don't currently have a branch for the 4.0.x range :-(

Lets wait until monday for this one, as this component is not used much at all.

And as v4.0.3 has only had 18 downloads in the last 7 days, this doesn't (seem) to be super critical
https://www.npmjs.com/package/@microsoft/applicationinsights-react-native?activeTab=versions

**Comment by MSNev** [comment]
We will also need to include a publish tag for the release (so it doesn't become the "latest").

**Pull request closed without merging**
